let num1 = "" + 1 + 0;
let num2 = "" - 1 + 0;
let num3 = true + false;
let num4 = 6 / "3";
let num5 = "2" * "3";
let num6 = 4 + 5 + "px";
let num7 = "$" + 4 + 5;
let num8 = "4" - 2;
let num9 = "4px" - 2;
let num10 = "  -9  " + 5;
let num11 = "  -9  " - 5 ;
let num12 = null + 1;
let num13 = undefined + 1;
let num14 = " \t \n" - 2;

console.log( "1. ", num1, "тип:", typeof num1);
console.log( "2. ", num2, "тип:", typeof num2 );
console.log( "3. ", num3, "тип:", typeof num3 );
console.log( "4. ", num4, "тип:", typeof num4 );
console.log( "5. ", num5, "тип:", typeof num5 );
console.log( "6. ", num6, "тип:", typeof num6 );
console.log( "7. ", num7, "тип:", typeof num7 );
console.log( "8. ", num8, "тип:", typeof num8 );
console.log( "9. ", num9, "тип:", typeof num9 );
console.log( "10. ", num10, "тип:", typeof num10 );
console.log( "11. ", num11, "тип:", typeof num11 );
console.log( "12. ", num12, "тип:", typeof num12 );
console.log( "13. ", num13, "тип:", typeof num13 );
console.log( "14. ", num14, "тип:", typeof num14 );